export const LOAD = 'INTERFACES_LOAD';
export const START_LOAD = 'INTERFACES_START_LOAD';
export const NEW_DOCKER = 'INTERFACES_NEW_DOCKER';
export const SET_DOCKER = 'INTERFACES_SET_DOCKER';
export const SET_LOG = 'INTERFACES_SET_LOG';
export const SET_HARDWARE = 'INTERFACES_SET_HARDWARE';
