export const LOAD = 'INTERFACES_LOAD';
export const SET_STATUS_CONNECT = 'INTERFACES_SET_STATUS_CONNECT';
export const SET_INFO = 'INTERFACES_SET_INFO';
export const SET_DOCKER = 'INTERFACES_SET_DOCKER';
export const SET_HARDWARE = 'INTERFACES_SET_HARDWARE';
export const SET_DRONE = 'INTERFACES_SET_DRONE';
